/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs;


import com.transfer.jooq.stubs.tables.Account;
import com.transfer.jooq.stubs.tables.Customer;
import com.transfer.jooq.stubs.tables.CustomerAccountLink;
import com.transfer.jooq.stubs.tables.TransactionLog;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_E = Indexes0.PRIMARY_KEY_E;
    public static final Index IDX_CE = Indexes0.IDX_CE;
    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;
    public static final Index FK_C2A_ACCOUNT_NUMBER_INDEX_E = Indexes0.FK_C2A_ACCOUNT_NUMBER_INDEX_E;
    public static final Index FK_C2A_CUSTOMER_ID_INDEX_E = Indexes0.FK_C2A_CUSTOMER_ID_INDEX_E;
    public static final Index PRIMARY_KEY_E5 = Indexes0.PRIMARY_KEY_E5;
    public static final Index FK_TX2A_ACCOUNT_NUMBER_INDEX_8 = Indexes0.FK_TX2A_ACCOUNT_NUMBER_INDEX_8;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_E = Internal.createIndex("PRIMARY_KEY_E", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ACCOUNT_NUMBER }, true);
        public static Index IDX_CE = Internal.createIndex("IDX_CE", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.FIRST_NAME, Customer.CUSTOMER.LAST_NAME }, true);
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.CUSTOMER_ID }, true);
        public static Index FK_C2A_ACCOUNT_NUMBER_INDEX_E = Internal.createIndex("FK_C2A_ACCOUNT_NUMBER_INDEX_E", CustomerAccountLink.CUSTOMER_ACCOUNT_LINK, new OrderField[] { CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.ACCOUNT_NUMBER }, false);
        public static Index FK_C2A_CUSTOMER_ID_INDEX_E = Internal.createIndex("FK_C2A_CUSTOMER_ID_INDEX_E", CustomerAccountLink.CUSTOMER_ACCOUNT_LINK, new OrderField[] { CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.CUSTOMER_ID }, false);
        public static Index PRIMARY_KEY_E5 = Internal.createIndex("PRIMARY_KEY_E5", CustomerAccountLink.CUSTOMER_ACCOUNT_LINK, new OrderField[] { CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.CUSTOMER_ID, CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.ACCOUNT_NUMBER }, true);
        public static Index FK_TX2A_ACCOUNT_NUMBER_INDEX_8 = Internal.createIndex("FK_TX2A_ACCOUNT_NUMBER_INDEX_8", TransactionLog.TRANSACTION_LOG, new OrderField[] { TransactionLog.TRANSACTION_LOG.ACCOUNT_NUMBER }, false);
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", TransactionLog.TRANSACTION_LOG, new OrderField[] { TransactionLog.TRANSACTION_LOG.TX_ID }, true);
    }
}
