/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs;


import com.transfer.jooq.stubs.tables.Account;
import com.transfer.jooq.stubs.tables.Customer;
import com.transfer.jooq.stubs.tables.CustomerAccountLink;
import com.transfer.jooq.stubs.tables.TransactionLog;
import com.transfer.jooq.stubs.tables.records.AccountRecord;
import com.transfer.jooq.stubs.tables.records.CustomerAccountLinkRecord;
import com.transfer.jooq.stubs.tables.records.CustomerRecord;
import com.transfer.jooq.stubs.tables.records.TransactionLogRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomerRecord, Long> IDENTITY_CUSTOMER = Identities0.IDENTITY_CUSTOMER;
    public static final Identity<TransactionLogRecord, Long> IDENTITY_TRANSACTION_LOG = Identities0.IDENTITY_TRANSACTION_LOG;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;
    public static final UniqueKey<CustomerAccountLinkRecord> PK_C2A = UniqueKeys0.PK_C2A;
    public static final UniqueKey<TransactionLogRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomerAccountLinkRecord, CustomerRecord> FK_C2A_CUSTOMER_ID = ForeignKeys0.FK_C2A_CUSTOMER_ID;
    public static final ForeignKey<CustomerAccountLinkRecord, AccountRecord> FK_C2A_ACCOUNT_NUMBER = ForeignKeys0.FK_C2A_ACCOUNT_NUMBER;
    public static final ForeignKey<TransactionLogRecord, AccountRecord> FK_TX2A_ACCOUNT_NUMBER = ForeignKeys0.FK_TX2A_ACCOUNT_NUMBER;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CustomerRecord, Long> IDENTITY_CUSTOMER = Internal.createIdentity(Customer.CUSTOMER, Customer.CUSTOMER.CUSTOMER_ID);
        public static Identity<TransactionLogRecord, Long> IDENTITY_TRANSACTION_LOG = Internal.createIdentity(TransactionLog.TRANSACTION_LOG, TransactionLog.TRANSACTION_LOG.TX_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> CONSTRAINT_E = Internal.createUniqueKey(Account.ACCOUNT, "CONSTRAINT_E", Account.ACCOUNT.ACCOUNT_NUMBER);
        public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = Internal.createUniqueKey(Customer.CUSTOMER, "CONSTRAINT_5", Customer.CUSTOMER.CUSTOMER_ID);
        public static final UniqueKey<CustomerAccountLinkRecord> PK_C2A = Internal.createUniqueKey(CustomerAccountLink.CUSTOMER_ACCOUNT_LINK, "PK_C2A", CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.CUSTOMER_ID, CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.ACCOUNT_NUMBER);
        public static final UniqueKey<TransactionLogRecord> CONSTRAINT_8 = Internal.createUniqueKey(TransactionLog.TRANSACTION_LOG, "CONSTRAINT_8", TransactionLog.TRANSACTION_LOG.TX_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CustomerAccountLinkRecord, CustomerRecord> FK_C2A_CUSTOMER_ID = Internal.createForeignKey(com.transfer.jooq.stubs.Keys.CONSTRAINT_5, CustomerAccountLink.CUSTOMER_ACCOUNT_LINK, "FK_C2A_CUSTOMER_ID", CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.CUSTOMER_ID);
        public static final ForeignKey<CustomerAccountLinkRecord, AccountRecord> FK_C2A_ACCOUNT_NUMBER = Internal.createForeignKey(com.transfer.jooq.stubs.Keys.CONSTRAINT_E, CustomerAccountLink.CUSTOMER_ACCOUNT_LINK, "FK_C2A_ACCOUNT_NUMBER", CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.ACCOUNT_NUMBER);
        public static final ForeignKey<TransactionLogRecord, AccountRecord> FK_TX2A_ACCOUNT_NUMBER = Internal.createForeignKey(com.transfer.jooq.stubs.Keys.CONSTRAINT_E, TransactionLog.TRANSACTION_LOG, "FK_TX2A_ACCOUNT_NUMBER", TransactionLog.TRANSACTION_LOG.ACCOUNT_NUMBER);
    }
}
