/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs;


import com.transfer.jooq.stubs.tables.Account;
import com.transfer.jooq.stubs.tables.Customer;
import com.transfer.jooq.stubs.tables.CustomerAccountLink;
import com.transfer.jooq.stubs.tables.TransactionLog;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -321488609;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public final Account ACCOUNT = com.transfer.jooq.stubs.tables.Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public final Customer CUSTOMER = com.transfer.jooq.stubs.tables.Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.CUSTOMER_ACCOUNT_LINK</code>.
     */
    public final CustomerAccountLink CUSTOMER_ACCOUNT_LINK = com.transfer.jooq.stubs.tables.CustomerAccountLink.CUSTOMER_ACCOUNT_LINK;

    /**
     * The table <code>PUBLIC.TRANSACTION_LOG</code>.
     */
    public final TransactionLog TRANSACTION_LOG = com.transfer.jooq.stubs.tables.TransactionLog.TRANSACTION_LOG;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SEQ_CUSTOMER_ID);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Customer.CUSTOMER,
            CustomerAccountLink.CUSTOMER_ACCOUNT_LINK,
            TransactionLog.TRANSACTION_LOG);
    }
}
