/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SEQ_CUSTOMER_ID</code>
     */
    public static final Sequence<Long> SEQ_CUSTOMER_ID = new SequenceImpl<Long>("SEQ_CUSTOMER_ID", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
