/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.daos;


import com.transfer.jooq.stubs.tables.Account;
import com.transfer.jooq.stubs.tables.records.AccountRecord;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountDao extends DAOImpl<AccountRecord, com.transfer.jooq.stubs.tables.pojos.Account, String> {

    /**
     * Create a new AccountDao without any configuration
     */
    public AccountDao() {
        super(Account.ACCOUNT, com.transfer.jooq.stubs.tables.pojos.Account.class);
    }

    /**
     * Create a new AccountDao with an attached configuration
     */
    public AccountDao(Configuration configuration) {
        super(Account.ACCOUNT, com.transfer.jooq.stubs.tables.pojos.Account.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.transfer.jooq.stubs.tables.pojos.Account object) {
        return object.getAccountNumber();
    }

    /**
     * Fetch records that have <code>ACCOUNT_NUMBER IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Account> fetchByAccountNumber(String... values) {
        return fetch(Account.ACCOUNT.ACCOUNT_NUMBER, values);
    }

    /**
     * Fetch a unique record that has <code>ACCOUNT_NUMBER = value</code>
     */
    public com.transfer.jooq.stubs.tables.pojos.Account fetchOneByAccountNumber(String value) {
        return fetchOne(Account.ACCOUNT.ACCOUNT_NUMBER, value);
    }

    /**
     * Fetch records that have <code>TYPE IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Account> fetchByType(String... values) {
        return fetch(Account.ACCOUNT.TYPE, values);
    }

    /**
     * Fetch records that have <code>DESCRIPTION IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Account> fetchByDescription(String... values) {
        return fetch(Account.ACCOUNT.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>BALANCE IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Account> fetchByBalance(BigDecimal... values) {
        return fetch(Account.ACCOUNT.BALANCE, values);
    }

    /**
     * Fetch records that have <code>CURRENCY_CODE IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Account> fetchByCurrencyCode(String... values) {
        return fetch(Account.ACCOUNT.CURRENCY_CODE, values);
    }

    /**
     * Fetch records that have <code>SOFT_DELETED IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Account> fetchBySoftDeleted(String... values) {
        return fetch(Account.ACCOUNT.SOFT_DELETED, values);
    }
}
