/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.daos;


import com.transfer.jooq.stubs.tables.Customer;
import com.transfer.jooq.stubs.tables.records.CustomerRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerDao extends DAOImpl<CustomerRecord, com.transfer.jooq.stubs.tables.pojos.Customer, Long> {

    /**
     * Create a new CustomerDao without any configuration
     */
    public CustomerDao() {
        super(Customer.CUSTOMER, com.transfer.jooq.stubs.tables.pojos.Customer.class);
    }

    /**
     * Create a new CustomerDao with an attached configuration
     */
    public CustomerDao(Configuration configuration) {
        super(Customer.CUSTOMER, com.transfer.jooq.stubs.tables.pojos.Customer.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.transfer.jooq.stubs.tables.pojos.Customer object) {
        return object.getCustomerId();
    }

    /**
     * Fetch records that have <code>CUSTOMER_ID IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Customer> fetchByCustomerId(Long... values) {
        return fetch(Customer.CUSTOMER.CUSTOMER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>CUSTOMER_ID = value</code>
     */
    public com.transfer.jooq.stubs.tables.pojos.Customer fetchOneByCustomerId(Long value) {
        return fetchOne(Customer.CUSTOMER.CUSTOMER_ID, value);
    }

    /**
     * Fetch records that have <code>FIRST_NAME IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Customer> fetchByFirstName(String... values) {
        return fetch(Customer.CUSTOMER.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>LAST_NAME IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Customer> fetchByLastName(String... values) {
        return fetch(Customer.CUSTOMER.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>EMAIL IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Customer> fetchByEmail(String... values) {
        return fetch(Customer.CUSTOMER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>SOFT_DELETED IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.Customer> fetchBySoftDeleted(String... values) {
        return fetch(Customer.CUSTOMER.SOFT_DELETED, values);
    }
}
