/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.daos;


import com.transfer.jooq.stubs.tables.TransactionLog;
import com.transfer.jooq.stubs.tables.records.TransactionLogRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionLogDao extends DAOImpl<TransactionLogRecord, com.transfer.jooq.stubs.tables.pojos.TransactionLog, Long> {

    /**
     * Create a new TransactionLogDao without any configuration
     */
    public TransactionLogDao() {
        super(TransactionLog.TRANSACTION_LOG, com.transfer.jooq.stubs.tables.pojos.TransactionLog.class);
    }

    /**
     * Create a new TransactionLogDao with an attached configuration
     */
    public TransactionLogDao(Configuration configuration) {
        super(TransactionLog.TRANSACTION_LOG, com.transfer.jooq.stubs.tables.pojos.TransactionLog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.transfer.jooq.stubs.tables.pojos.TransactionLog object) {
        return object.getTxId();
    }

    /**
     * Fetch records that have <code>TX_ID IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.TransactionLog> fetchByTxId(Long... values) {
        return fetch(TransactionLog.TRANSACTION_LOG.TX_ID, values);
    }

    /**
     * Fetch a unique record that has <code>TX_ID = value</code>
     */
    public com.transfer.jooq.stubs.tables.pojos.TransactionLog fetchOneByTxId(Long value) {
        return fetchOne(TransactionLog.TRANSACTION_LOG.TX_ID, value);
    }

    /**
     * Fetch records that have <code>ACCOUNT_NUMBER IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.TransactionLog> fetchByAccountNumber(String... values) {
        return fetch(TransactionLog.TRANSACTION_LOG.ACCOUNT_NUMBER, values);
    }

    /**
     * Fetch records that have <code>AMOUNT IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.TransactionLog> fetchByAmount(BigDecimal... values) {
        return fetch(TransactionLog.TRANSACTION_LOG.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>BALANCE IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.TransactionLog> fetchByBalance(BigDecimal... values) {
        return fetch(TransactionLog.TRANSACTION_LOG.BALANCE, values);
    }

    /**
     * Fetch records that have <code>TIME_STAMP IN (values)</code>
     */
    public List<com.transfer.jooq.stubs.tables.pojos.TransactionLog> fetchByTimeStamp(Timestamp... values) {
        return fetch(TransactionLog.TRANSACTION_LOG.TIME_STAMP, values);
    }
}
