/*
 * This file is generated by jOOQ.
 */
package com.transfer.entity;

import com.google.common.base.Objects;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;


public class TransactionLog implements Serializable {

    private static final long serialVersionUID = 211247371418598810L;

    private Long       txId;
    private Long fromAccountNumber;
    private Long toAccountNumber;
    private BigDecimal amount;
    private Timestamp  timeStamp;

    public TransactionLog() {}

    public TransactionLog(TransactionLog value) {
        this.txId = value.txId;
        this.fromAccountNumber = value.fromAccountNumber;
        this.toAccountNumber = value.toAccountNumber;
        this.amount = value.amount;
        this.timeStamp = value.timeStamp;
    }

    public TransactionLog(
        Long       fromAccountNumber,
        Long       toAccountNumber,
        BigDecimal amount,
        Timestamp  timeStamp
    ) {
        this.fromAccountNumber = fromAccountNumber;
        this.toAccountNumber = toAccountNumber;
        this.amount = amount;
        this.timeStamp = timeStamp;
    }

    public Long getTxId() {
        return this.txId;
    }

    public void setTxId(Long txId) {
        this.txId = txId;
    }

    public Long getFromAccountNumber() {
        return this.fromAccountNumber;
    }

    public void setFromAccountNumber(Long fromAccountNumber) {
        this.fromAccountNumber = fromAccountNumber;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Timestamp getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Timestamp timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getToAccountNumber() {
        return toAccountNumber;
    }

    public void setToAccountNumber(Long toAccountNumber) {
        this.toAccountNumber = toAccountNumber;
    }

    @Override
    public String toString() {
        return "TransactionLog{" +
                "txId=" + txId +
                ", fromAccountNumber=" + fromAccountNumber +
                ", toAccountNumber=" + toAccountNumber +
                ", amount=" + amount +
                ", timeStamp=" + timeStamp +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TransactionLog)) return false;
        TransactionLog that = (TransactionLog) o;
        return Objects.equal(txId, that.txId) &&
                Objects.equal(fromAccountNumber, that.fromAccountNumber) &&
                Objects.equal(toAccountNumber, that.toAccountNumber) &&
                Objects.equal(amount, that.amount) &&
                Objects.equal(timeStamp, that.timeStamp);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(txId, fromAccountNumber, toAccountNumber, amount, timeStamp);
    }
}
