/*
 * This file is generated by jOOQ.
 */
package com.transfer.entity;

import com.google.common.base.Objects;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;


public class TransactionLog implements Serializable {

    private static final long serialVersionUID = -1572979739;

    private Long       txId;
    private Long       accountId;
    private BigDecimal amount;
    private BigDecimal balance;
    private Timestamp  timeStamp;

    public TransactionLog() {}

    public TransactionLog(TransactionLog value) {
        this.txId = value.txId;
        this.accountId = value.accountId;
        this.amount = value.amount;
        this.balance = value.balance;
        this.timeStamp = value.timeStamp;
    }

    public TransactionLog(
        Long       txId,
        Long       accountId,
        BigDecimal amount,
        BigDecimal balance,
        Timestamp  timeStamp
    ) {
        this.txId = txId;
        this.accountId = accountId;
        this.amount = amount;
        this.balance = balance;
        this.timeStamp = timeStamp;
    }

    public Long getTxId() {
        return this.txId;
    }

    public void setTxId(Long txId) {
        this.txId = txId;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public Timestamp getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Timestamp timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransactionLog (");

        sb.append(txId);
        sb.append(", ").append(accountId);
        sb.append(", ").append(amount);
        sb.append(", ").append(balance);
        sb.append(", ").append(timeStamp);

        sb.append(")");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TransactionLog)) return false;
        TransactionLog that = (TransactionLog) o;
        return Objects.equal(txId, that.txId) &&
                Objects.equal(accountId, that.accountId) &&
                Objects.equal(amount, that.amount) &&
                Objects.equal(balance, that.balance) &&
                Objects.equal(timeStamp, that.timeStamp);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(txId, accountId, amount, balance, timeStamp);
    }
}
