/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 200796223;

    private String     accountNumber;
    private String     type;
    private String     description;
    private BigDecimal balance;
    private String     currencyCode;
    private String     softDeleted;

    public Account() {}

    public Account(Account value) {
        this.accountNumber = value.accountNumber;
        this.type = value.type;
        this.description = value.description;
        this.balance = value.balance;
        this.currencyCode = value.currencyCode;
        this.softDeleted = value.softDeleted;
    }

    public Account(
        String     accountNumber,
        String     type,
        String     description,
        BigDecimal balance,
        String     currencyCode,
        String     softDeleted
    ) {
        this.accountNumber = accountNumber;
        this.type = type;
        this.description = description;
        this.balance = balance;
        this.currencyCode = currencyCode;
        this.softDeleted = softDeleted;
    }

    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public String getSoftDeleted() {
        return this.softDeleted;
    }

    public void setSoftDeleted(String softDeleted) {
        this.softDeleted = softDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(accountNumber);
        sb.append(", ").append(type);
        sb.append(", ").append(description);
        sb.append(", ").append(balance);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(softDeleted);

        sb.append(")");
        return sb.toString();
    }
}
