/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerAccountLink implements Serializable {

    private static final long serialVersionUID = 1567528890;

    private Long   customerId;
    private String accountNumber;

    public CustomerAccountLink() {}

    public CustomerAccountLink(CustomerAccountLink value) {
        this.customerId = value.customerId;
        this.accountNumber = value.accountNumber;
    }

    public CustomerAccountLink(
        Long   customerId,
        String accountNumber
    ) {
        this.customerId = customerId;
        this.accountNumber = accountNumber;
    }

    public Long getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerAccountLink (");

        sb.append(customerId);
        sb.append(", ").append(accountNumber);

        sb.append(")");
        return sb.toString();
    }
}
