/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer implements Serializable {

    private static final long serialVersionUID = -1172034493;

    private Long   customerId;
    private String firstName;
    private String lastName;
    private String email;
    private String softDeleted;

    public Customer() {}

    public Customer(Customer value) {
        this.customerId = value.customerId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.email = value.email;
        this.softDeleted = value.softDeleted;
    }

    public Customer(
        Long   customerId,
        String firstName,
        String lastName,
        String email,
        String softDeleted
    ) {
        this.customerId = customerId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.softDeleted = softDeleted;
    }

    public Long getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSoftDeleted() {
        return this.softDeleted;
    }

    public void setSoftDeleted(String softDeleted) {
        this.softDeleted = softDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(customerId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(softDeleted);

        sb.append(")");
        return sb.toString();
    }
}
