/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionLog implements Serializable {

    private static final long serialVersionUID = 1782255579;

    private Long       txId;
    private String     accountNumber;
    private BigDecimal amount;
    private BigDecimal balance;
    private Timestamp  timeStamp;

    public TransactionLog() {}

    public TransactionLog(TransactionLog value) {
        this.txId = value.txId;
        this.accountNumber = value.accountNumber;
        this.amount = value.amount;
        this.balance = value.balance;
        this.timeStamp = value.timeStamp;
    }

    public TransactionLog(
        Long       txId,
        String     accountNumber,
        BigDecimal amount,
        BigDecimal balance,
        Timestamp  timeStamp
    ) {
        this.txId = txId;
        this.accountNumber = accountNumber;
        this.amount = amount;
        this.balance = balance;
        this.timeStamp = timeStamp;
    }

    public Long getTxId() {
        return this.txId;
    }

    public void setTxId(Long txId) {
        this.txId = txId;
    }

    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public Timestamp getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Timestamp timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransactionLog (");

        sb.append(txId);
        sb.append(", ").append(accountNumber);
        sb.append(", ").append(amount);
        sb.append(", ").append(balance);
        sb.append(", ").append(timeStamp);

        sb.append(")");
        return sb.toString();
    }
}
