/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.records;


import com.transfer.jooq.stubs.tables.CustomerAccountLink;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerAccountLinkRecord extends UpdatableRecordImpl<CustomerAccountLinkRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -2011561613;

    /**
     * Setter for <code>PUBLIC.CUSTOMER_ACCOUNT_LINK.CUSTOMER_ID</code>.
     */
    public void setCustomerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER_ACCOUNT_LINK.CUSTOMER_ID</code>.
     */
    public Long getCustomerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CUSTOMER_ACCOUNT_LINK.ACCOUNT_NUMBER</code>.
     */
    public void setAccountNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CUSTOMER_ACCOUNT_LINK.ACCOUNT_NUMBER</code>.
     */
    public String getAccountNumber() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CustomerAccountLink.CUSTOMER_ACCOUNT_LINK.ACCOUNT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountLinkRecord value1(Long value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountLinkRecord value2(String value) {
        setAccountNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountLinkRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerAccountLinkRecord
     */
    public CustomerAccountLinkRecord() {
        super(CustomerAccountLink.CUSTOMER_ACCOUNT_LINK);
    }

    /**
     * Create a detached, initialised CustomerAccountLinkRecord
     */
    public CustomerAccountLinkRecord(Long customerId, String accountNumber) {
        super(CustomerAccountLink.CUSTOMER_ACCOUNT_LINK);

        set(0, customerId);
        set(1, accountNumber);
    }
}
