/*
 * This file is generated by jOOQ.
 */
package com.transfer.jooq.stubs.tables.records;


import com.transfer.jooq.stubs.tables.TransactionLog;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionLogRecord extends UpdatableRecordImpl<TransactionLogRecord> implements Record5<Long, String, BigDecimal, BigDecimal, Timestamp> {

    private static final long serialVersionUID = 198133037;

    /**
     * Setter for <code>PUBLIC.TRANSACTION_LOG.TX_ID</code>.
     */
    public void setTxId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSACTION_LOG.TX_ID</code>.
     */
    public Long getTxId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TRANSACTION_LOG.ACCOUNT_NUMBER</code>.
     */
    public void setAccountNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSACTION_LOG.ACCOUNT_NUMBER</code>.
     */
    public String getAccountNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TRANSACTION_LOG.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSACTION_LOG.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TRANSACTION_LOG.BALANCE</code>.
     */
    public void setBalance(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSACTION_LOG.BALANCE</code>.
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>PUBLIC.TRANSACTION_LOG.TIME_STAMP</code>.
     */
    public void setTimeStamp(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSACTION_LOG.TIME_STAMP</code>.
     */
    public Timestamp getTimeStamp() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, BigDecimal, BigDecimal, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, BigDecimal, BigDecimal, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TransactionLog.TRANSACTION_LOG.TX_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TransactionLog.TRANSACTION_LOG.ACCOUNT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return TransactionLog.TRANSACTION_LOG.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TransactionLog.TRANSACTION_LOG.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TransactionLog.TRANSACTION_LOG.TIME_STAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getTxId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getTimeStamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getTxId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getTimeStamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionLogRecord value1(Long value) {
        setTxId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionLogRecord value2(String value) {
        setAccountNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionLogRecord value3(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionLogRecord value4(BigDecimal value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionLogRecord value5(Timestamp value) {
        setTimeStamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionLogRecord values(Long value1, String value2, BigDecimal value3, BigDecimal value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionLogRecord
     */
    public TransactionLogRecord() {
        super(TransactionLog.TRANSACTION_LOG);
    }

    /**
     * Create a detached, initialised TransactionLogRecord
     */
    public TransactionLogRecord(Long txId, String accountNumber, BigDecimal amount, BigDecimal balance, Timestamp timeStamp) {
        super(TransactionLog.TRANSACTION_LOG);

        set(0, txId);
        set(1, accountNumber);
        set(2, amount);
        set(3, balance);
        set(4, timeStamp);
    }
}
